In [3]:

# coding: utf-8

# In[1]:


import nltk
import math
import io
import gensim
from gensim import * 
from nltk.tokenize import word_tokenize, sent_tokenize, RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

final_words=[]
'''UTILITY FUNCTIONS'''
def intersection(lst1, lst2):
    return len(list(set(lst1) & set(lst2))) 

def union(a,b):
    return(len(set(a).union(set(b))))

def tokenizeWords(fcontent):
    tokenizer=RegexpTokenizer(r'\w+')
    word_tokens=[]
    word_tokens=tokenizer.tokenize(fcontent)
    return word_tokens

def removeStopWords(word_tokens):
    stop_words=set(stopwords.words('english'))
    filtered_words=[]
    for w in word_tokens:
        if w not in stop_words:
            filtered_words.append(w)
    return filtered_words

def lemmatize(filtered_words):
    lem_words=[]
    lemmatizer=WordNetLemmatizer()
    for w in filtered_words:
        word=(lemmatizer.lemmatize(w))
        lem_words.append(word.lower())
    return lem_words

def copyfinal(lem_words):
    final_words.append(lem_words)

def newBigramList(lem_words):
    length=len(lem_words)
    new_list=[]
    for i in range(0,length-1):
        new_list.append(lem_words[i]+lem_words[i+1])
    return new_list

def distance(a,b):
    dist=0
    for i in range(0,4):
        dist=dist+((a[i]-b[i])**2)
    dist=math.sqrt(dist)
    return dist


#driver code
doc_count=0
docwords=[]
choice=1
while(choice==1):
    #accepting file and reading its content
    name=input('Enter filename: \n')
    fp=open(name,'r')
    fcontent=fp.read()
    doc_count+=1
    #tokenizing
    word_tokens=tokenizeWords(fcontent)
    fp.close()

    #removing stop words
    filtered_words=removeStopWords(word_tokens)
    #lemmatizing
    lem_words=lemmatize(filtered_words)
    copyfinal(lem_words)
    lem_words=newBigramList(lem_words)
    docwords.append(lem_words)
    choice=int(input("Add another file? (0 or 1): "))

print("Documents are given")
print(docwords)


#Word2Vec

import gensim
model=gensim.models.Word2Vec(docwords,min_count=1,size=4)
print(choice)
X= model[model.wv.vocab]
print(X)


# KMEANSCLUSTER

from nltk.cluster import KMeansClusterer
NUM_CLUSTERS=100
kclusterer = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
assigned_clusters = kclusterer.cluster(X, assign_clusters=True)
print (assigned_clusters)


#Wordcluster is a dictionary with cluster no as keys and list of words as values 

words = list(model.wv.vocab)
wordcluster={}
for i in range(0,100):
    wordcluster.update({i:[]})
for i, word in enumerate(words):  
    print (word + ":" + str(assigned_clusters[i]))


for i,word in enumerate(words):
    wordcluster[assigned_clusters[i]].append(word)
print(wordcluster)



    


Enter filename: 
1
Add another file? (0 or 1): 1
Enter filename: 
2
Add another file? (0 or 1): 1
Enter filename: 
3
Add another file? (0 or 1): 1
Enter filename: 
4
Add another file? (0 or 1): 1
Enter filename: 
5
Add another file? (0 or 1): 1
Enter filename: 
6
Add another file? (0 or 1): 1
Enter filename: 
7
Add another file? (0 or 1): 1
Enter filename: 
8
Add another file? (0 or 1): 1
Enter filename: 
9
Add another file? (0 or 1): 1
Enter filename: 
10
Add another file? (0 or 1): 1
Enter filename: 
11
Add another file? (0 or 1): 1
Enter filename: 
12
Add another file? (0 or 1): 1
Enter filename: 
13
Add another file? (0 or 1): 1
Enter filename: 
14
Add another file? (0 or 1): 1
Enter filename: 
15
Add another file? (0 or 1): 1
Enter filename: 
16
Add another file? (0 or 1): 1
Enter filename: 
17
Add another file? (0 or 1): 1
Enter filename: 
18
Add another file? (0 or 1): 1
Enter filename: 
19
Add another file? (0 or 1): 1
Enter filename: 
20
Add another file? (0 or 1): 1
Enter fil

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:93: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


[97, 39, 73, 0, 2, 65, 92, 66, 31, 7, 84, 72, 6, 15, 75, 77, 33, 71, 79, 87, 56, 63, 48, 72, 88, 41, 70, 35, 60, 63, 72, 96, 21, 28, 51, 93, 35, 43, 50, 3, 58, 91, 99, 40, 49, 0, 58, 66, 89, 46, 22, 98, 68, 32, 70, 14, 5, 33, 84, 84, 5, 71, 48, 54, 22, 95, 72, 53, 73, 36, 77, 78, 77, 86, 74, 66, 3, 12, 99, 49, 27, 49, 87, 42, 57, 1, 22, 13, 88, 48, 77, 71, 49, 23, 26, 43, 77, 53, 85, 92, 53, 22, 72, 28, 65, 99, 63, 70, 89, 24, 29, 87, 15, 0, 98, 59, 90, 37, 30, 17, 4, 21, 3, 48, 51, 60, 40, 15, 83, 39, 55, 99, 51, 86, 27, 81, 70, 23, 3, 60, 16, 33, 77, 88, 89, 95, 92, 77, 18, 10, 50, 19, 22, 53, 20, 38, 7, 87, 50, 98, 95, 10, 40, 73, 5, 64, 73, 72, 78, 4, 84, 49, 26, 60, 29, 71, 14, 27, 49, 23, 28, 13, 35, 35, 61, 89, 52, 67, 89, 43, 10, 60, 38, 90, 22, 74, 36, 46, 7, 6, 80, 58, 79, 77, 65, 21, 85, 9, 23, 52, 54, 55, 26, 32, 14, 91, 12, 36, 64, 37, 92, 17, 86, 98, 50, 52, 69, 6, 14, 58, 16, 54, 91, 6, 40, 0, 99, 62, 81, 66, 95, 22, 12, 56, 89, 49, 88, 1, 38, 8, 41, 35, 75, 82, 52, 5, 3

In [4]:
total_words=0
for i in range(0,100):
  total_words=total_words+len(wordcluster[i])
  print(str(i)+"  :"+str(len(wordcluster[i])))
  
print("Total words "+str(total_words))

0  :135
1  :171
2  :157
3  :164
4  :217
5  :169
6  :180
7  :138
8  :151
9  :167
10  :148
11  :143
12  :127
13  :170
14  :151
15  :159
16  :146
17  :148
18  :149
19  :142
20  :156
21  :156
22  :165
23  :166
24  :137
25  :139
26  :150
27  :154
28  :127
29  :174
30  :131
31  :157
32  :185
33  :166
34  :166
35  :167
36  :129
37  :180
38  :157
39  :169
40  :135
41  :128
42  :150
43  :132
44  :186
45  :167
46  :143
47  :125
48  :147
49  :183
50  :153
51  :193
52  :184
53  :160
54  :113
55  :153
56  :180
57  :135
58  :160
59  :165
60  :136
61  :124
62  :161
63  :140
64  :153
65  :177
66  :161
67  :140
68  :181
69  :166
70  :161
71  :172
72  :157
73  :153
74  :153
75  :188
76  :97
77  :156
78  :137
79  :174
80  :137
81  :123
82  :132
83  :157
84  :153
85  :191
86  :163
87  :158
88  :126
89  :169
90  :195
91  :137
92  :167
93  :142
94  :132
95  :136
96  :170
97  :128
98  :156
99  :157
Total words 15471


In [5]:
document_clusters={}
for i in range(1,doc_count+1):
  document_clusters.update({i:[0 for i in range(0,100)]})
print(document_clusters)

{1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 2: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 3: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 4: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [6]:
for i in range(0,doc_count):
  for j in range(0,100):
    for w in wordcluster[j]:
      if w in docwords[i]:
        document_clusters[i+1][j]=document_clusters[i+1][j]+1

print(document_clusters)

{1: [2, 1, 1, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 4, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 3, 4, 1, 1, 0, 3, 1, 0, 1, 1, 2, 0, 1, 0, 0, 3, 0, 2, 3, 0, 1, 0, 3, 3, 5, 2, 1, 1, 0, 5, 1, 1, 0, 0, 0, 0, 3, 1, 1, 2, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 3], 2: [2, 1, 0, 2, 3, 3, 3, 2, 1, 1, 4, 3, 2, 3, 3, 2, 4, 2, 1, 1, 1, 4, 3, 3, 4, 0, 2, 3, 2, 2, 2, 0, 1, 2, 0, 4, 2, 3, 4, 1, 3, 1, 0, 2, 0, 0, 2, 1, 1, 3, 3, 3, 4, 1, 3, 2, 2, 0, 2, 2, 4, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 3, 3, 1, 1, 4, 1, 2, 1, 3, 1, 1, 2, 2, 2, 2, 2, 6, 3, 2, 3, 0, 1, 4, 0, 0, 3, 3], 3: [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], 4: [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,

In [0]:
f=open("finalvectors.txt","w+")
for i in document_clusters.keys():
  b=''
  for j in document_clusters[i]:
    b=b+str(j)+','
  b=b[0:len(b)-1]
  f.write(b+'\n')
f.close()

def distancevectors(d1,d2):
  dist=0
  for i in range(0,100):
    dist=dist+((d1[i]-d2[i])**2)
  dist=math.sqrt(dist)
  return dist


In [8]:
distancedict=[]
a=[]
for i in range(1,doc_count+1):
  for j in range(i+1,doc_count+1):
    a=[i,j,distancevectors(document_clusters[i],document_clusters[j])]
    distancedict.append(a)
print(distancedict)
    

[[1, 2, 18.439088914585774], [1, 3, 15.132745950421556], [1, 4, 13.856406460551018], [1, 5, 14.933184523068078], [1, 6, 14.594519519326424], [1, 7, 15.362291495737216], [1, 8, 18.193405398660254], [1, 9, 20.760539492026695], [1, 10, 14.2828568570857], [1, 11, 13.711309200802088], [1, 12, 17.320508075688775], [1, 13, 18.16590212458495], [1, 14, 23.62202362203543], [1, 15, 22.090722034374522], [1, 16, 14.66287829861518], [1, 17, 15.588457268119896], [1, 18, 14.594519519326424], [1, 19, 67.59437846448475], [1, 20, 14.798648586948742], [1, 21, 16.61324772583615], [1, 22, 14.422205101855956], [1, 23, 18.027756377319946], [1, 24, 15.459624833740307], [1, 25, 15.297058540778355], [1, 26, 14.2828568570857], [1, 27, 150.63864046120437], [1, 28, 14.696938456699069], [1, 29, 20.346989949375804], [1, 30, 13.856406460551018], [1, 31, 16.64331697709324], [1, 32, 12.806248474865697], [1, 33, 16.0], [1, 34, 15.362291495737216], [1, 35, 16.24807680927192], [1, 36, 15.684387141358123], [1, 37, 14.899664

In [0]:
def average(worddist):
    avg=0
    for a in worddist:
        avg=avg+a[2]
    avg=avg/len(worddist)
    return avg

In [0]:
threshold=average(distancedict)
fs=open("Finaldata.txt","w")
for i in distancedict:
  if (i[2]>threshold):
    fs.write(str(i[0])+' '+str(i[1])+'\n')
fs.close()

In [11]:
distancelist=[]
for i in range(1,doc_count+1):
  distancelist.append(document_clusters[i])
print(distancelist)

[[2, 1, 1, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 4, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 3, 4, 1, 1, 0, 3, 1, 0, 1, 1, 2, 0, 1, 0, 0, 3, 0, 2, 3, 0, 1, 0, 3, 3, 5, 2, 1, 1, 0, 5, 1, 1, 0, 0, 0, 0, 3, 1, 1, 2, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 3], [2, 1, 0, 2, 3, 3, 3, 2, 1, 1, 4, 3, 2, 3, 3, 2, 4, 2, 1, 1, 1, 4, 3, 3, 4, 0, 2, 3, 2, 2, 2, 0, 1, 2, 0, 4, 2, 3, 4, 1, 3, 1, 0, 2, 0, 0, 2, 1, 1, 3, 3, 3, 4, 1, 3, 2, 2, 0, 2, 2, 4, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 3, 3, 1, 1, 4, 1, 2, 1, 3, 1, 1, 2, 2, 2, 2, 2, 6, 3, 2, 3, 0, 1, 4, 0, 0, 3, 3], [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [12]:
import numpy as np
myarray = np.asarray(distancelist)
print(myarray)

[[2 1 1 ... 1 1 3]
 [2 1 0 ... 0 3 3]
 [0 1 0 ... 0 0 0]
 ...
 [3 4 1 ... 4 1 0]
 [1 1 0 ... 3 0 2]
 [1 0 0 ... 0 0 0]]


In [40]:
NUM_CLUSTERS=2
kclusterer = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=15)
assigned_clusters = kclusterer.cluster(myarray, assign_clusters=True)
print (assigned_clusters)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]


In [41]:
for i in range(0,100):
  print("Document "+str(i+1)+"  :  Cluster  "+str(assigned_clusters[i]))

Document 1  :  Cluster  0
Document 2  :  Cluster  0
Document 3  :  Cluster  0
Document 4  :  Cluster  0
Document 5  :  Cluster  0
Document 6  :  Cluster  0
Document 7  :  Cluster  0
Document 8  :  Cluster  0
Document 9  :  Cluster  0
Document 10  :  Cluster  0
Document 11  :  Cluster  0
Document 12  :  Cluster  0
Document 13  :  Cluster  0
Document 14  :  Cluster  0
Document 15  :  Cluster  0
Document 16  :  Cluster  0
Document 17  :  Cluster  0
Document 18  :  Cluster  0
Document 19  :  Cluster  1
Document 20  :  Cluster  0
Document 21  :  Cluster  0
Document 22  :  Cluster  0
Document 23  :  Cluster  0
Document 24  :  Cluster  0
Document 25  :  Cluster  0
Document 26  :  Cluster  0
Document 27  :  Cluster  1
Document 28  :  Cluster  0
Document 29  :  Cluster  0
Document 30  :  Cluster  0
Document 31  :  Cluster  0
Document 32  :  Cluster  0
Document 33  :  Cluster  0
Document 34  :  Cluster  0
Document 35  :  Cluster  0
Document 36  :  Cluster  0
Document 37  :  Cluster  0
Document 3

In [0]:
def dist(a,b):
  import math
  n=len(a)
  k=0
  for i in range(0,n):
    k=k+((a[i]-b[i])**2)
  return math.sqrt(k)
def db(X,clusters):
  n=len(X)
  cno=0
  temp=[]
  for i in clusters:
    if i not in temp:
      cno=cno+1
      temp.append(i)
  index=0
  centroid=[]
  for i in range(0,cno):
    cc=[]
    count=0
    k=0
    for j in range(0,n):
      if (clusters[j]==i):
        cc=X[j]
        k=j
        count=count+1
        break
    for j in range(0,n):
      if (clusters[j]==i) and (k!=j):
        cc=cc+X[j]
        count=count+1
    cc=cc/count
    centroid.append(cc)
  cluster=[]
  for i in range(0,cno):
    cluster.append([])
  for i in range(0,cno):
    for j in range(0,n):
      if (clusters[j]==i):
        cluster[i].append(j)
  selfcluster=[]
  for i in range(0,cno):
    k=0
    for j in cluster[i]:
      k=k+dist(X[j],centroid[i])
    k=k/len(cluster[i])
    selfcluster.append(k)
  diff=[]
  for i in range(0,cno):
    a=[]
    for j in range(0,cno):
      a.append(dist(centroid[i],centroid[j]))
    diff.append(a)
  index=[]
  for i in range(0,cno):
    a=[]
    for j in range(0,cno):
      if (i==j):
        a.append(0)
      else:
        k=(selfcluster[i]+selfcluster[j])/diff[i][j]
        a.append(k)
    index.append(a)
  value=[0,0]
  for i in range(0,cno):
    value[0]=value[0]+max(index[i])
  value[0]=value[0]/cno
  den=max(selfcluster)
  new=[]
  for i in range(0,cno):
    for j in diff[i]:
      if (j!=0):
        new.append(j)
  num=min(new)
  value[1]=num/den
  print(value)  
  return value


In [42]:
value=db(myarray,assigned_clusters)
print(value[0])
print(value[1])

[0.6675038310451453, 1.8918855006346156]
0.6675038310451453
1.8918855006346156


In [28]:
from sklearn.metrics import davies_bouldin_score
from nltk.cluster import KMeansClusterer
NUM_CLUSTERS=5
kclusterer = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
assigned_clusters = kclusterer.cluster(myarray, assign_clusters=True)
print (assigned_clusters)
davies_bouldin_score(myarray, assigned_clusters)


[1, 2, 0, 0, 0, 0, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 3, 0, 1, 1, 1, 0, 0, 0, 4, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 2, 2, 0, 3, 1, 1, 0, 1, 2, 0, 0, 1, 1, 3, 3, 0, 0, 1, 1, 1, 2, 0, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1, 3, 1, 2, 0, 0, 2, 1, 2, 0, 4, 1, 0, 0, 1, 1, 0, 0]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


1.5696200289362363